version: '3.8'

services:
  # Laravel PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./vendor:/var/www/vendor
    networks:
      - laravel

  # Nginx Service to Serve Laravel App
  web:
    image: nginx:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: bookreview-hub  
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

  # Node.js for Vue.js Compilation
  node:
    image: node:21.7.3
    container_name: node-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: npm run dev
    networks:
      - laravel


networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
